apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cbchart.fullname" . }}
  labels:
    {{- include "cbchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cbchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cbchart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data-storage
              mountPath: /app/uploads
            - name: db-storage
              mountPath: /app/data
      volumes:
        - name: data-storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "cbchart.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: db-storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "cbchart.fullname" . }}-db
          {{- else }}
          emptyDir: {}
          {{- end }}
